<Project Sdk="Microsoft.NET.Sdk.Razor">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Markdig" Version="0.40.0" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.FluentUI.AspNetCore.Components" Version="4.11.1" />
        <PackageReference Include="Microsoft.FluentUI.AspNetCore.Components.Emoji" Version="4.11.1" />
        <PackageReference Include="Microsoft.FluentUI.AspNetCore.Components.Icons" Version="4.11.1" />
    </ItemGroup>
    
    <ItemGroup>
      <ProjectReference Include="..\TabbyCat.Service\TabbyCat.Service.csproj" />
      <ProjectReference Include="..\TabbyCat.VisualBase\TabbyCat.VisualBase.csproj" />
    </ItemGroup>

    <ItemGroup>
      <Folder Include="Pages\" />
    </ItemGroup>

    <ItemGroup>
        <SupportedPlatform Include="browser" />
    </ItemGroup>

    <ItemGroup>
      <MauiCss Remove="Components\ChatInput.razor.css" />
      <Content Include="Components\ChatInput.razor.css" />
      <MauiCss Remove="Components\AiSettingPanel.razor.css" />
      <Content Include="Components\AiSettingPanel.razor.css" />
    </ItemGroup>
    

</Project>
