name: publish-macos

on:
  push:
    branches: [ "RabbitPublish" ]

jobs:
  build:

    runs-on: macos-latest

    env:
      Solution_Name: TabbyCat.sln      # 你的解决方案路径
      Project_Path: UpdateProgram/YouYan.Rabbit    # 你的主项目路径
      
  
    steps:
    - name: Checkout 代码
      uses: actions/checkout@v4
      with:
        fetch-depth: 0   # 获取完整提交历史，以便提取提交日志

    - name: 安装 .NET SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x

    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set VERSION
      run: echo "VERSION=$(date +'%Y.%m.%d.%H%M%S')" >> $GITHUB_ENV
    
    - name: Install the Apple certificate and provisioning profile
      env:
        BUILD_CERTIFICATE_BASE64: ${{ secrets.MACOS_CERTIFICATE_BASE64 }}
        P12_PASSWORD: ${{ secrets.MACOS_CERTIFICATE_PASSWORD }}
        BUILD_PROVISION_PROFILE_BASE64: ${{ secrets.RABBIT_BUILD_PROVISION_PROFILE_BASE64 }}
        KEYCHAIN_PASSWORD: ${{ secrets.KEYCHAIN_PASSWORD }}
      run: |
        # create variables
        CERTIFICATE_PATH=$RUNNER_TEMP/build_certificate.p12
        PP_PATH=$RUNNER_TEMP/build_pp.mobileprovision
        KEYCHAIN_PATH=$RUNNER_TEMP/app-signing.keychain-db
        
        # import certificate and provisioning profile from secrets
        echo -n "$BUILD_CERTIFICATE_BASE64" | base64 --decode -o $CERTIFICATE_PATH
        echo -n "$BUILD_PROVISION_PROFILE_BASE64" | base64 --decode -o $PP_PATH
        
        # create temporary keychain
        security create-keychain -p "$KEYCHAIN_PASSWORD" $KEYCHAIN_PATH
        security set-keychain-settings -lut 21600 $KEYCHAIN_PATH
        security unlock-keychain -p "$KEYCHAIN_PASSWORD" $KEYCHAIN_PATH
        
        # import certificate to keychain
        security import $CERTIFICATE_PATH -P "$P12_PASSWORD" -A -t cert -f pkcs12 -k $KEYCHAIN_PATH
        security set-key-partition-list -S apple-tool:,apple: -k "$KEYCHAIN_PASSWORD" $KEYCHAIN_PATH
        security list-keychain -d user -s $KEYCHAIN_PATH
        
        # apply provisioning profile
        mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
        cp $PP_PATH ~/Library/MobileDevice/Provisioning\ Profiles

    - name: Build and Create .app Bundle
      run: | 
        PROJECT_NAME="YouYan.Rabbit"
        OUTPUT_DIR="$Project_Path/bin/Release/net9.0/osx-arm64/publish"
        
        echo "Building for osx-arm64..."
        dotnet publish $Project_Path/$PROJECT_NAME.csproj -r osx-arm64 -c Release --self-contained -p:UseAppHost=true
        
        echo "Creating the .app bundle..."
        APP_NAME="Rabbit.app"
        CONTENT_PATH="$Project_Path/$APP_NAME/Contents"
        MACOS_PATH="$CONTENT_PATH/MacOS"
        RESOURCES_PATH="$CONTENT_PATH/Resources"
        
        echo "content path :$CONTENT_PATH"

        mkdir -p "$MACOS_PATH"
        mkdir -p "$RESOURCES_PATH"

        cp "$OUTPUT_DIR/$PROJECT_NAME" "$MACOS_PATH/"
        cp -R "$OUTPUT_DIR/" "$MACOS_PATH/"
        cp -R "$OUTPUT_DIR/"*.dylib "$MACOS_PATH/" 2>/dev/null || true
        echo "$VERSION" > "$MACOS_PATH/v"

        if [ -d "$OUTPUT_DIR/Resources" ]; then
            cp -R "$OUTPUT_DIR/Resources" "$RESOURCES_PATH/"
        fi

        if [ -d "$OUTPUT_DIR/Assets" ]; then
            cp -R "$OUTPUT_DIR/Assets" "$RESOURCES_PATH/"
        fi

        if [ -f "$Project_Path/app.icns" ]; then
            echo "Copying app.icns to Resources..."
            cp "$Project_Path/app.icns" "$RESOURCES_PATH/"
        fi

        cat <<EOF > "$CONTENT_PATH/Info.plist"
        <?xml version="1.0" encoding="UTF-8"?>
        <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
        <plist version="1.0">
            <dict>
                <key>CFBundleIconFile</key>
                <string>app.icns</string>
                <key>CFBundleIdentifier</key>
                <string>com.youyan.rabbit</string>
                <key>CFBundleName</key>
                <string>Rabbit</string>
                <key>CFBundleVersion</key>
                <string>1.0.0</string>
                <key>LSMinimumSystemVersion</key>
                <string>10.12</string>
                <key>CFBundleExecutable</key>
                <string>YouYan.Rabbit</string>
                <key>CFBundleInfoDictionaryVersion</key>
                <string>6.0</string>
                <key>CFBundlePackageType</key>
                <string>APPL</string>
                <key>CFBundleShortVersionString</key>
                <string>1.0</string>
                <key>NSHighResolutionCapable</key>
                <true/>
            </dict>
        </plist>
        EOF
        cat <<EOF > "$CONTENT_PATH/entitlements.plist"
        <?xml version="1.0" encoding="UTF-8"?>
        <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
        <plist version="1.0">
        <dict>
            <key>com.apple.security.cs.allow-jit</key>
            <true/>
            <key>com.apple.security.cs.allow-unsigned-executable-memory</key>
            <true/>
            <key>com.apple.security.cs.disable-library-validation</key>
            <true/>
            <key>com.apple.security.cs.allow-dyld-environment-variables</key>
            <true/>
            <key>com.apple.security.network.client</key>
            <true/>
            <key>com.apple.security.network.server</key>
            <true/>
            <key>com.apple.security.files.user-selected.read-write</key>
            <true/>
        </dict>
        </plist>
        EOF

        echo "Making application executable..."
        chmod +x "$MACOS_PATH/YouYan.Rabbit"

    - name: Code Sign Application
      run: |
        codesign --force --deep --entitlements "UpdateProgram/YouYan.Rabbit/Rabbit.app/Contents/entitlements.plist" --sign "Developer ID Application: liujun fang (7443K5WM8B)" --options=runtime UpdateProgram/YouYan.Rabbit/Rabbit.app
    
    - name: Create DMG for distribution
      run: |
        # 定义路径
        APP_PATH="UpdateProgram/YouYan.Rabbit/Rabbit.app"
        DMG_NAME="Rabbit.dmg"
        VOLUME_NAME="Rabbit"
        TEMP_DIR="build_dmg"
        
        # 清理旧目录
        rm -rf "$TEMP_DIR"
        mkdir -p "$TEMP_DIR"
        
        # 拷贝 .app 到临时目录
        cp -R "$APP_PATH" "$TEMP_DIR/"
        
        # 创建 /Applications 快捷方式
        ln -s /Applications "$TEMP_DIR/Applications"
        
        # 创建 .dmg 文件
        hdiutil create \
        -volname "$VOLUME_NAME" \
        -srcfolder "$TEMP_DIR" \
        -ov \
        -format UDZO \
        "UpdateProgram/YouYan.Rabbit/$DMG_NAME"
        rm -rf "$TEMP_DIR"

    - name: Submitting DMG for notarization
      run: |
        xcrun notarytool submit "UpdateProgram/YouYan.Rabbit/Rabbit.dmg" \
        --wait \
        --apple-id "snsaiu@outlook.com" \
        --password "ozvk-mzka-vqlg-ayku" \
        --team-id "7443K5WM8B"
        
    - name: Staple the notarization to the DMG
      run: |
        xcrun stapler staple "UpdateProgram/YouYan.Rabbit/Rabbit.dmg"
        

    - name: Package .dmg into ZIP
      run: |
        if ls "$Project_Path"/*.dmg 1> /dev/null 2>&1; then
          cd "$Project_Path"
          zip -r app-release.zip *.dmg
        else
          echo "❌ Error: No .dmg files found in $Project_Path"
          exit 1
        fi

    - name: Verify ZIP Creation
      run: |
        if [ -f "$Project_Path/app-release.zip" ]; then
          echo "✅ ZIP file exists."
        else
          echo "❌ ZIP file does not exist."
          exit 1
        fi
        

    - name: 设置环境变量
      run: |
        echo "RELEASE_NOTES<<EOF" >> $GITHUB_ENV
        git log -1 --pretty=%B >> $GITHUB_ENV
        echo "EOF" >> $GITHUB_ENV

    - name: Upload zip as artifact
      uses: actions/upload-artifact@v4
      with:
        name: rabbit-macOS-DMG
        path: UpdateProgram/YouYan.Rabbit/app-release.zip

    - name: Upload zip package and metadata
      run: |
        echo "🔎 RELEASE_NOTES: $RELEASE_NOTES"
        echo "🔎 VERSION: $VERSION"
        
        FILE="UpdateProgram/YouYan.Rabbit/app-release.zip"
        CHUNK_SIZE=$((20 * 1024 * 1024)) # 20MB
        TOTAL_SIZE=$(stat -f%z "$FILE")
        START_BYTE=0
        
        RELEASE_NOTES="$(git log -1 --pretty=%B)"
     
        echo "🔎 文件总大小：$TOTAL_SIZE 字节"
        echo "🔎 RELEASE_NOTES: $RELEASE_NOTES"
        echo "🔎 VERSION: $VERSION"
        
        while [ $START_BYTE -lt $TOTAL_SIZE ]; do
          END_BYTE=$((START_BYTE + CHUNK_SIZE - 1))
          [ $END_BYTE -ge $TOTAL_SIZE ] && END_BYTE=$((TOTAL_SIZE - 1))
          CHUNK_FILE="chunk_${START_BYTE}_${END_BYTE}.zip"
        
          dd if="$FILE" of="$CHUNK_FILE" bs=1 skip=$START_BYTE count=$((END_BYTE - START_BYTE + 1)) status=none
        
          echo "⬆️ 上传分片 $START_BYTE - $END_BYTE"
        
          RESPONSE=$(curl -s -X POST "${{ secrets.UPLOAD_APP_URL }}" \
            -F "file=@$CHUNK_FILE" \
            -F "description=$RELEASE_NOTES" \
            -F "appName=Rabbit" \
            -F "osType=1" \
            -F "version=$VERSION" \
            -F "startByte=$START_BYTE" \
            -F "endByte=$END_BYTE" \
            -F "totalSize=$TOTAL_SIZE")
        
          echo "✅ 上传成功，响应：$RESPONSE"
        
          rm "$CHUNK_FILE"
          START_BYTE=$((END_BYTE + 1))
        done
